# **Theoretical Questions :**


---



#### ***Q.1 Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?***

**Ans :-** NumPy (Numerical Python) is a fundamental library in Python for scientific computing and data analysis. It provides support for large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays efficiently. NumPy’s array object, known as ndarray, is particularly optimized for performance, making it significantly faster and more memory-efficient than traditional Python lists for handling large datasets. Here’s a breakdown of its purpose and advantages:

**Purpose of NumPy**
  * **Efficient Array Operations :** It enables the creation and manipulation of large arrays and matrices with complex calculations and high efficiency.
  * **Foundational Library :** NumPy serves as the foundation for other popular data science libraries (e.g., Pandas, SciPy, TensorFlow), providing core array functionality.
  * **Standard for Numerical Data:** Many scientific computing workflows rely on NumPy arrays as their core data structure due to their flexibility and speed.
  * **Interoperability:** NumPy is widely compatible with other libraries, and it allows for easy integration with C/C++ and Fortran code, which can further optimize performance.

**Advantages of Using NumPy**
  1. **Speed and Efficiency:**
    * NumPy uses highly optimized C and Fortran code, making it much faster than native Python for operations on large datasets.
    * It enables element-wise operations on arrays without requiring loops in Python, leveraging vectorized operations for better performance.

  2.  **Memory Efficiency:**
    * ndarray objects are more memory-efficient than Python lists as they store data in contiguous blocks of memory, reducing memory overhead.
    * It uses fixed data types for each element (e.g., integers, floats), which optimizes both speed and memory.

  3.  **Vectorization and Broadcasting:**
    * **Vectorization:** By eliminating the need for explicit loops, NumPy's vectorized operations allow complex calculations to be expressed succinctly and executed faster.
    * **Broadcasting:** This feature enables arithmetic operations on arrays of different shapes without copying data, allowing for efficient use of memory and CPU.

  4.  **Comprehensive Mathematical Functions:**
    * NumPy includes numerous mathematical functions (e.g., linear algebra, Fourier transformations, random number generation) that are optimized for large datasets.
    * It supports complex operations like matrix multiplication, element-wise operations, and statistical calculations, enabling users to perform sophisticated analyses with minimal code.

  5.  **Data Manipulation:**
     * NumPy arrays can be reshaped, sliced, and indexed efficiently, making them versatile for preprocessing data before feeding it into machine learning models or performing statistical analyses.

  6.  **Ecosystem Integration:**
    * Libraries such as Pandas, Matplotlib, and SciPy are built on top of NumPy arrays, making it easier to transition between data manipulation, visualization, and advanced scientific computation.

**How NumPy Enhances Python for Numerical Operations**
  
  NumPy effectively transforms Python into a high-performance computing language by enabling optimized, low-level calculations directly in Python. This lets Python code operate nearly as fast as compiled code, such as C or Fortran, when working with numerical data. Additionally, NumPy’s API simplifies complex mathematical and scientific tasks, making Python a popular choice for data science, machine learning, and scientific research.

#### ***Q.2 Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?***

**Ans :-** In NumPy, `np.mean()` and `np.average()` both calculate the average of array elements, but they have differences in functionality and usage, especially when dealing with weighted averages. Here’s a detailed comparison of each function:

1. **np.mean()**
  * **Definition:** `np.mean()` computes the arithmetic mean (simple average) of array elements along a specified axis or for the entire array.
  * **Syntax:**
```
  np.mean(array, axis=None)
```
  * **Parameters:**
      * array: The input array.
      * axis (optional): Specifies the axis along which to compute the mean. If axis=None (default), it computes the mean of all elements in the array.
  * **Output:** The simple average of array elements, computed as the sum of the elements divided by their count.
   * **Usage:** `np.mean()` is used for simple averages where each element is equally weighted.
```
Example:
        import numpy as np
        arr = np.array([1, 2, 3, 4])
        np.mean(arr)  # Output: 2.5
```
2. **np.average()**
  * **Definition:** `np.average()` computes the weighted average of array elements if weights are provided; otherwise, it defaults to calculating the simple average, like `np.mean()`.
  * **Syntax:**
```
np.average(array, weights=None, axis=None)
```
  * **Parameters:**
      * array: The input array.
      * weights (optional): A 1-D array of weights that specifies the relative importance of each element. If weights=None (default), `np.average()` behaves like `np.mean()`.
      * axis (optional): Specifies the axis along which to compute the average. If axis=None, it computes the average of all elements.
  * **Output:** The weighted average if weights are provided; otherwise, the simple average.
  * **Usage:** `np.average()` is particularly useful for weighted averages, allowing specific elements to contribute more or less to the final result.
```
Example:
        arr = np.array([1, 2, 3, 4])
        weights = np.array([1, 2, 3, 4])
        np.average(arr, weights=weights)  # Output: 3.0
```

**When to Use `np.mean()` vs. `np.average()`**
  * Use `np.mean()` when you need a straightforward, unweighted average.
  * Use `np.average()` when you need a weighted average, or if there is a possibility of using weights in future code adaptations. If no weights are provided, `np.average()` functions the same as `np.mean()`.

#### ***Q.3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.***

**Ans :-** In NumPy, We can reverse an array along various axes using slicing, the `np.flip()` function, or specific axis arguments for multi-dimensional arrays. Here’s how to reverse arrays along different axes, with examples for both 1D and 2D arrays:

1. **Reversing a 1D Array**
  For a 1D array, reversing the array simply means flipping it in the reverse order.
  * **Using slicing:**
```
    import numpy as np
    arr = np.array([1, 2, 3, 4, 5])
    reversed_arr = arr[::-1]
    print(reversed_arr)  # Output: [5 4 3 2 1]
```
  * **Using `np.flip()`:**
```
    reversed_arr = np.flip(arr)
    print(reversed_arr)  # Output: [5 4 3 2 1]
```
Both methods achieve the same result for a 1D array, reversing the order of elements.

2. **Reversing a 2D Array :-**
  For 2D arrays, we can reverse along specific axes (rows or columns) or flip the entire array.
  * **Reversing Along Rows (Axis 0) :-**  This operation flips the rows in reverse order.
    * Using slicing:
```
  arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
  reversed_rows = arr_2d[::-1, :]
  print(reversed_rows)
  # Output:
  # [[7 8 9]
  #  [4 5 6]
  #  [1 2 3]]
```
    * **Using `np.flip()` with axis=0 :-**
```
  reversed_rows = np.flip(arr_2d, axis=0)
  print(reversed_rows)
  # Output:
  # [[7 8 9]
  #  [4 5 6]
  #  [1 2 3]]
```
  * **Reversing Along Columns (Axis 1) :-** This operation flips the columns in reverse order.
    * Using slicing:
```
  reversed_columns = arr_2d[:, ::-1]
  print(reversed_columns)
  # Output:
  # [[3 2 1]
  #  [6 5 4]
  #  [9 8 7]]
```
    * Using np.flip() with axis=1:
```
  reversed_columns = np.flip(arr_2d, axis=1)
  print(reversed_columns)
  # Output:
  # [[3 2 1]
  #  [6 5 4]
  #  [9 8 7]]
```
  * **Reversing Both Axes :-** To reverse the entire 2D array (both rows and columns), we can combine both row and column reversals.
    * Using slicing:
```
  reversed_all = arr_2d[::-1, ::-1]
  print(reversed_all)
  # Output:
  # [[9 8 7]
  #  [6 5 4]
  #  [3 2 1]]
```
    * Using np.flip() without specifying an axis:
```
  reversed_all = np.flip(arr_2d)
  print(reversed_all)
  # Output:
  # [[9 8 7]
  #  [6 5 4]
  #  [3 2 1]]
```

#### ***Q.4 How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.***

**Ans :-** To determine the data type of elements in a NumPy array, we can use the `.dtype` attribute of the array. This will return the data type of the array elements, such as `int32`, `float64`, or `bool`.

**Example of Checking Data Type :-**
```
import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4])

# Checking the data type
print(arr.dtype)  # Output: int64 (or int32, depending on the platform)
```

**Importance of Data Types in NumPy :-** Data types (or dtypes in NumPy) play a critical role in both memory management and performance optimization.

1. **Memory Management :-** Each data type in NumPy is associated with a specific memory size. Choosing an appropriate data type allows you to manage memory more efficiently, especially with large datasets.
  * **Memory Consumption:** For instance, an int8 array (8 bits per element) consumes four times less memory than an int32 array (32 bits per element). Therefore, using smaller data types when appropriate can lead to substantial memory savings.
  * **Efficient Storage:** This is particularly beneficial in cases where precision is not critical, such as using int16 or float32 instead of their larger counterparts int64 or float64.
```
Example:
        arr_float32 = np.array([1.0, 2.0, 3.0], dtype=np.float32)  # Each element uses 4 bytes
        arr_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)  # Each element uses 8 bytes
        print(arr_float32.nbytes)  # Output: 12 bytes (3 * 4)
        print(arr_float64.nbytes)  # Output: 24 bytes (3 * 8)
```
2. **Performance Optimization :-** The data type also directly influences computational speed.
  * **Lower Precision, Faster Computation:** Smaller data types like int16 or float32 require less computational power than int64 or float64, making operations on such arrays faster. This is particularly relevant in applications like machine learning and real-time data analysis, where processing speed is critical.
  * **Vectorized Operations:** NumPy is optimized for specific data types, enabling it to leverage vectorized operations and SIMD (Single Instruction, Multiple Data) in underlying libraries (e.g., BLAS, LAPACK). Using the optimal data type maximizes these efficiencies.
```
Example:
        # Creating large arrays with different dtypes
        arr_int32 = np.ones(10**6, dtype=np.int32)
        arr_int64 = np.ones(10**6, dtype=np.int64)
        # Timing addition operation
        %timeit arr_int32 + arr_int32  # Generally faster due to lower memory bandwidth requirement
        %timeit arr_int64 + arr_int64  # Slower for larger dtypes
```

#### ***Q.5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?***

**Ans :-** In NumPy, an ndarray (N-dimensional array) is the core data structure used for storing and manipulating data. Unlike Python lists, which are flexible and can store mixed data types, ndarrays are designed specifically for efficient numerical computations and are a key element for scientific computing in Python.

**Key Features of ndarray in NumPy**
1.  **Homogeneous Data Type :-**
      * All elements in an ndarray must be of the same data type, such as int32, float64, or bool.
      * This uniformity allows for efficient memory storage and faster processing, as operations are optimized for the specific data type.
2.  **N-dimensional :-**
      * ndarray objects can have any number of dimensions, from 1D (vectors) to 2D (matrices) and even higher dimensions (e.g., 3D tensors for image processing).
      * The dimensions are determined by the array’s shape, which is a tuple of integers indicating the size along each dimension.
3.  **Fixed Size :-**
      * Once an ndarray is created, its size (total number of elements) cannot be changed. You can reshape it (change the arrangement of elements without changing the total count), but the underlying data remains the same.
4.  **Efficient Memory Layout :-**
      * ndarray stores data in contiguous blocks of memory, which improves memory locality and enables vectorized operations. This memory efficiency is key to fast computation.
      * The data layout also allows for broadcasting, where operations can apply across arrays of different shapes in a way that avoids data duplication.
5.  **Vectorized Operations :-**
      * NumPy supports vectorized operations, allowing you to apply mathematical functions across an entire array without explicit loops. This makes ndarray operations significantly faster than their Python list counterparts, especially with large datasets.
6.  **Advanced Indexing and Slicing :-**
      * ndarray provides powerful indexing and slicing capabilities that let you access and manipulate data along any axis and retrieve subarrays without creating copies.
      * We can use slicing, boolean indexing, and fancy indexing to select specific parts of an array efficiently.

**Differences Between `ndarray` and Python Lists**
1.  Data Type :-
  * `ndarray` in NumPy : Homogeneous; all elements must be of the same type.
  * Python Lists : Heterogeneous; can store different data types.
2.  Memory Efficiency
  * `ndarray` in NumPy : Stores data in contiguous memory, reducing memory usage.
  * Python Lists : Uses separate memory blocks for each element, increasing overhead.
3.  Speed
  * `ndarray` in NumPy :  Optimized for numerical computations, with fast, vectorized operations.
  * Python Lists : Slower for large numerical computations, as it lacks vectorization.
4.  Dimensionality :
  * `ndarray` in NumPy :  Supports multiple dimensions (1D, 2D, …, nD).
  * Python Lists : Typically 1D; can hold nested lists for 2D/3D, but inefficient.
5.  Fixed Size :
  * `ndarray` in NumPy :  Size is fixed after creation; can be reshaped but not resized.
  * Python Lists : Dynamic size; elements can be added or removed easily.
6.  Broadcasting :
  * `ndarray` in NumPy :  Supports broadcasting for operations on arrays of different shapes.
  * Python Lists : No native support for broadcasting; operations require manual looping.
7.  Element-wise Operations :
  * `ndarray` in NumPy :  Supports element-wise operations directly.
  * Python Lists : Requires looping or comprehension for element-wise operations.


In [1]:
# Example: Comparison of ndarray and Python List Performance

import numpy as np
import time

# NumPy ndarray
arr_np = np.arange(1, 1000001)

# Python list
arr_list = list(range(1, 1000001))

# Squaring elements (NumPy)
start = time.time()
arr_np ** 2
end = time.time()
print("NumPy Time:", end - start)

# Squaring elements (Python list)
start = time.time()
[x ** 2 for x in arr_list]
end = time.time()
print("Python List Time:", end - start)

NumPy Time: 0.007399320602416992
Python List Time: 0.34877467155456543


#### ***Q.6 Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.***

**Ans :-** NumPy arrays (ndarrays) offer significant performance advantages over Python lists, especially for large-scale numerical operations. These benefits stem from several factors, including memory efficiency, optimized C and Fortran implementations, vectorized operations, and broadcasting. Let’s analyze these advantages in detail:

1. **Memory Efficiency :-**
  * **Compact Storage:** NumPy arrays are stored in contiguous memory blocks, unlike Python lists, where each element is a separate object with its own metadata (e.g., type information, reference count). This compact storage of data allows NumPy to reduce memory overhead.
  * **Fixed Data Types:** Each element in a NumPy array is of a fixed data type (e.g., int32, float64), which conserves memory since NumPy does not need to store type information for each element individually. Python lists, in contrast, can hold mixed data types, which increases memory usage as each element’s data type must be individually stored.

**Example: Memory Usage Comparison**
```
import numpy as np
import sys

# Python list
list_data = [i for i in range(1000000)]
print("Python List Memory (MB):", sys.getsizeof(list_data) / (1024 ** 2))

# NumPy array
array_data = np.arange(1000000)
print("NumPy Array Memory (MB):", array_data.nbytes / (1024 ** 2))
```
2. **Computational Speed :-**
  * **Vectorized Operations:** NumPy supports vectorized operations, meaning that mathematical operations can be applied directly to entire arrays without needing explicit loops. Vectorization allows operations to be performed at the compiled C level, which is significantly faster than looping in pure Python.
  * **Avoids Python Overheads:** For large datasets, Python lists require looping through each element, which introduces interpreter overhead. NumPy bypasses this overhead by performing array operations directly in optimized C and Fortran code.

**Example: Computational Speed Comparison**
```
import time

# Creating large datasets
list_data = [i for i in range(1000000)]
array_data = np.arange(1000000)

# Squaring each element with Python list
start = time.time()
list_squared = [x ** 2 for x in list_data]
end = time.time()
print("Python List Time:", end - start)

# Squaring each element with NumPy array
start = time.time()
array_squared = array_data ** 2
end = time.time()
print("NumPy Array Time:", end - start)
```
3. **Broadcasting :-**
  * **Broadcasting Mechanism :** NumPy’s broadcasting allows operations on arrays of different shapes without manually reshaping or looping, making calculations simpler and more efficient. Broadcasting avoids unnecessary memory duplication and increases speed by allowing NumPy to perform operations on arrays as if they were the same shape.
  * **Example of Broadcasting :** Adding a scalar to each element of a large array or performing element-wise operations between differently shaped arrays is seamless with broadcasting, while in Python lists, it requires additional code and is slower.
```
# Adding a scalar to a large array with broadcasting
large_array = np.arange(1000000).reshape(1000, 1000)
scalar = 10
broadcast_result = large_array + scalar  # Fast with broadcasting
# Equivalent in pure Python requires nested loops and is slower
```
4. **Use of Low-Level Libraries :-**
  * **Optimized Libraries :** NumPy operations are linked to optimized low-level libraries like BLAS and LAPACK, which are highly efficient for linear algebra and matrix operations. This linkage allows NumPy to leverage highly optimized assembly or machine-level code for numerical computations, leading to performance gains that are impossible to achieve with pure Python.

5. **Parallelization :-**
  * **Support for SIMD :** Many of NumPy’s operations are designed to take advantage of SIMD (Single Instruction, Multiple Data) in modern CPUs, which allows the processor to perform the same operation on multiple data points simultaneously. This hardware acceleration is generally absent in Python’s built-in lists.

#### ***Q.7 Compare `vstack()` and `hstack()` functions in NumPy. Provide examples demonstrating their usage and output.***

**Ans :-** In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. They are part of the NumPy stacking functions and are useful for combining arrays along different axes.
1. **`np.vstack():` Vertical Stacking**
  * **Description :** The `vstack()` function stacks arrays vertically along a new row, or axis 0. It combines arrays by adding them as rows one after another.
  * **Requirements:** Arrays must have the same number of columns (or the same shape along axis 1) to be vertically stacked.

**Example of `vstack()`**
```
import numpy as np

# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Using vstack to stack vertically
result = np.vstack((arr1, arr2))
print(result)
# Output:
# [[1 2 3]
#  [4 5 6]]
```
Here, `vstack()` takes `arr1` and `arr2` and stacks them one on top of the other, creating a 2x3 array.

**Example with 2D arrays**
```
# Creating two 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stacking 2D arrays vertically
result = np.vstack((arr1, arr2))
print(result)
# Output:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]
```
2. **`np.hstack()`: Horizontal Stacking**
  * **Description:** The `hstack()` function stacks arrays horizontally along a new column, or axis 1. It combines arrays by placing them side by side.
  * **Requirements:** Arrays must have the same number of rows (or the same shape along axis 0) to be horizontally stacked.

**Example of `hstack()`**
```
# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Using hstack to stack horizontally
result = np.hstack((arr1, arr2))
print(result)
# Output:
# [1 2 3 4 5 6]
```
Here, `hstack()` takes arr1 and arr2 and joins them side by side to form a 1D array.

**Example with 2D arrays**
```
# Creating two 2D arrays with the same number of rows
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stacking 2D arrays horizontally
result = np.hstack((arr1, arr2))
print(result)
# Output:
# [[ 1  2  3  7  8  9]
#  [ 4  5  6 10 11 12]]
```

#### ***Q.8 Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.***

**Ans :-** In NumPy, `fliplr()` and `flipud()` are used to reverse the order of elements in an array along specific axes. Their names indicate their actions: `fliplr()` is for flipping left-to-right, and `flipud()` is for flipping up-to-down. These functions operate on 2D arrays and higher, with their effect differing based on the axis along which they flip elements.

1. **`np.fliplr():` Flip Left-to-Right**
  * **Description:** The `fliplr()` function reverses the order of columns in a 2D array or higher-dimensional array. It flips the array horizontally, meaning it swaps the columns from left to right.
  * **Effect on Dimensions:** The number of rows remains the same, but the columns are reversed. Each row is independently reversed along its axis.

**Example of `fliplr()` on a 2D Array**
```
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Using fliplr
result = np.fliplr(arr)
print(result)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]
```
In this example, each row is reversed horizontally (columns are reordered left-to-right).

**Example with a 3D Array**

For a 3D array, `fliplr()` only flips along the last axis (columns).
```
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]]])

result = np.fliplr(arr_3d)
print(result)
# Output:
# [[[4 5 6]
#   [1 2 3]]
#
#  [[10 11 12]
#   [ 7  8  9]]]
```
Here, each subarray’s rows have their columns flipped left-to-right.

2. **`np.flipud():` Flip Up-to-Down**
  * **Description:** The `flipud()` function reverses the order of rows in a 2D array or higher-dimensional array. It flips the array vertically, meaning it swaps rows from top to bottom.
  * **Effect on Dimensions:** The number of columns remains the same, but the rows are reversed. Each column is independently reversed along its axis.

**Example of `flipud()` on a 2D Array**
```
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Using flipud
result = np.flipud(arr)
print(result)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]
```
In this example, the rows are flipped vertically (the order of rows is reversed from top to bottom).

**Example with a 3D Array**

For a 3D array, `flipud()` only flips along the first axis (rows).
```
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]]])

result = np.flipud(arr_3d)
print(result)
# Output:
# [[[ 7  8  9]
#   [10 11 12]]
#
#  [[ 1  2  3]
#   [ 4  5  6]]]
```
Here, the two main "layers" are flipped, reversing their order top-to-bottom.

#### ***Q.9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?***

**Ans :-** The `np.array_split()` function in NumPy is used to split an array into multiple sub-arrays. Unlike `np.split()`, which requires that the split sizes be even, `array_split()` is flexible and can handle uneven splits. This is particularly useful when the array cannot be divided equally by the specified number of sections.
```
Syntax

np.array_split(array, indices_or_sections, axis=0)
```
  * **array:** The input array to be split.
  * **indices_or_sections:** The number of sections to split the array into or a list of specific indices at which to split.
  * **axis:** The axis along which the split is performed (default is 0 for row-wise split).

**Handling of Uneven Splits :-** When the size of the array cannot be divided evenly by the specified number of sections, `array_split()` automatically distributes the remaining elements across the initial sub-arrays, making some sub-arrays larger than others. The extra elements are added one by one to the earlier sub-arrays.

**Example of Uneven Splits**
```
import numpy as np

# Creating an array with 10 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Splitting into 3 sections (10 elements cannot be divided evenly by 3)
result = np.array_split(arr, 3)
print(result)
# Output:
# [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8, 9, 10])]
```
In this example, the 10 elements are split into three sub-arrays, with the extra element added to the first sub-array. This results in sub-arrays of sizes [4, 3, 3] rather than equal-sized splits.
Example with a 2D Array

When splitting along a specific axis, `array_split()` divides along the specified dimension. For instance, with a 2D array:
```
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Splitting into 2 sections along columns (axis=1)
result = np.array_split(arr_2d, 2, axis=1)
print(result)
# Output:
# [array([[ 1,  2],
#         [ 5,  6],
#         [ 9, 10]]),
#  array([[ 3,  4],
#         [ 7,  8],
#         [11, 12]])]
```
Here, `array_split()` divides the columns into two sections along axis=1. Each sub-array contains two columns, resulting in an equal split.

#### ***Q.10 Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?***

**Ans :-** Vectorization and broadcasting are two powerful concepts in NumPy that significantly enhance the efficiency of array operations, particularly in scientific computing and data analysis. Here’s an explanation of both concepts and their contributions to efficient array manipulation.

**Vectorization**
* **Definition:** Vectorization refers to the process of converting scalar operations (operations on single elements) into array operations (operations on whole arrays) without explicit loops. In NumPy, vectorization allows you to apply operations to entire arrays at once, leveraging optimized low-level implementations for performance gains.
* **Benefits:**
  1. **Performance Improvement:** Vectorized operations in NumPy are executed at a lower level (often in C or Fortran) and are optimized for performance. This leads to significant speedups compared to traditional Python loops.
  2. **Simpler Code:** Vectorization results in cleaner, more concise code, making it easier to read and maintain. You can apply mathematical operations directly to arrays instead of iterating through elements manually.

**Example of Vectorization :**
```
import numpy as np

# Creating two large arrays
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# Vectorized addition
c = a + b  # Adds corresponding elements of a and b

# Without vectorization (using a loop)
c_non_vectorized = np.empty(1000000)
for i in range(1000000):
    c_non_vectorized[i] = a[i] + b[i]
```
In this example, the vectorized operation a + b is much faster and more concise than using a for loop.

**Broadcasting**

* **Definition :** Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes. When operating on arrays of different sizes, NumPy automatically expands (broadcasts) the smaller array across the larger array so that they have compatible shapes.

**Rules of Broadcasting :**
  1. If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on the left side until both shapes are the same.
  2.  The arrays are compatible when:
       *  Their dimensions are equal, or
       *  One of the dimensions is 1.

**Benefits :**
  * **Memory Efficiency :** Broadcasting avoids unnecessary memory allocation by not actually replicating the smaller array. Instead, it creates a view of the data that appears to be larger.
  * **Ease of Use:** It simplifies code by allowing arithmetic operations without the need for explicit looping or reshaping of arrays.

**Example of Broadcasting :**
```
import numpy as np

# Creating a 1D array (vector)
a = np.array([1, 2, 3])

# Creating a 2D array (matrix)
b = np.array([[10], [20], [30]])

# Broadcasting: adding a vector to each row of a matrix
result = a + b
print(result)
# Output:
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]
```
In this example, the 1D array a is broadcasted across the rows of the 2D array b, allowing the addition to be performed as if a were repeated for each row.

**Contribution to Efficient Array Operations**
* **Reduced Computational Overhead:** Both vectorization and broadcasting eliminate the need for explicit loops in Python, significantly reducing computational overhead and improving execution speed.
* **Optimized Performance:** Operations are typically executed in compiled languages like C or Fortran behind the scenes, making them faster than equivalent Python code.
* **Increased Code Clarity:** Both techniques lead to more readable and maintainable code, allowing users to express complex operations succinctly.
* **Support for Large Data:** They enable efficient handling of large datasets common in scientific computing, machine learning, and data analysis.

# **Practical Questions :**


---



#### ***Q.1  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.***

**Ans :-**

In [2]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

print("Original Array:")
print(array_3x3)

# Interchange rows and columns (transpose)
transposed_array = array_3x3.T

print("\nTransposed Array (Rows and Columns Interchanged):")
transposed_array

Original Array:
[[100  75  16]
 [ 39  98  15]
 [ 67  39  65]]

Transposed Array (Rows and Columns Interchanged):


array([[100,  39,  67],
       [ 75,  98,  39],
       [ 16,  15,  65]])

#### ***Q.2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.***

**Ans :-**

In [3]:
import numpy as np

# Generate a 1D array with 10 elements
arr_1d = np.arange(10)

# Reshape to 2x5
arr_2x5 = arr_1d.reshape(2, 5)
print("2x5 array:")
print(arr_2x5)

# Reshape to 5x2
arr_5x2 = arr_2x5.reshape(5, 2)
print("\n5x2 array:")
arr_5x2

2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 array:


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### ***Q.3  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.***

**Ans :-**

In [4]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

array_6x6

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.94883512, 0.30800052, 0.79943306, 0.15293262,
        0.        ],
       [0.        , 0.50619225, 0.70231703, 0.84771375, 0.39337445,
        0.        ],
       [0.        , 0.5231151 , 0.97946671, 0.66348402, 0.56943178,
        0.        ],
       [0.        , 0.55556563, 0.9662528 , 0.15713956, 0.53043061,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

#### ***Q.4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.***

**Ans :-**

In [5]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
result_array = np.arange(10, 61, 5)

result_array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

#### ***Q.5  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.***

**Ans :-**

In [6]:
# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
swapcase_array = np.char.swapcase(string_array)

print("Original array:", string_array)
print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Titlecase:", titlecase_array)
print("Swapcase:", swapcase_array)

Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Titlecase: ['Python' 'Numpy' 'Pandas']
Swapcase: ['PYTHON' 'NUMPY' 'PANDAS']


#### ***Q.6 Generate a NumPy array of words. Insert a space between each character of every word in the array.***

**Ans :-**

In [7]:
import numpy as np

# Original array of words
words = np.array(['hello', 'world', 'numpy'])

# Insert spaces between characters using a list comprehension and join
spaced_words = np.array([ ' '.join(list(word)) for word in words])

spaced_words

array(['h e l l o', 'w o r l d', 'n u m p y'], dtype='<U9')

#### ***Q.7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.***

**Ans :-**

In [8]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition_result = array1 + array2
print("Addition:\n", addition_result)

# Element-wise subtraction
subtraction_result = array1 - array2
print("\nSubtraction:\n", subtraction_result)

# Element-wise multiplication
multiplication_result = array1 * array2
print("\nMultiplication:\n", multiplication_result)

# Element-wise division
division_result = array1 / array2
print("\nDivision:\n", division_result)

Addition:
 [[ 8 10 12]
 [14 16 18]]

Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


#### ***Q.8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.***

**Ans :-**

In [9]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


#### ***Q.9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.***

**Ans :-**

In [12]:
import numpy as np

def is_prime_num(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime_num(num)]

print("Random integers:", random_integers)
print("\nPrime numbers in the array:", prime_numbers)

Random integers: [917 904 663 719 889 628  41 846 337 334 469 573 652 209 965 769 195 690
 768 935 832 295 430 906 945 439 898 800 383 545 433  85 976  82 797 359
 888 694 201 130 357 755 988 721 621 514 857 192 942 833 787 151 617 198
 173 219 378 188 438 928 940 697 637 422 147 153 561 841 175 402 807 577
  57 917 795 852 459 226 418 600 280 977 761 933 141 252   2 338 273 633
 138 685 916 628 516 193 589 620 922 629]

Prime numbers in the array: [719, 41, 337, 769, 439, 383, 433, 797, 359, 857, 787, 151, 617, 173, 577, 977, 761, 2, 193]


#### ***Q.10  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.***

**Ans :-**

In [14]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)  # Example temperatures between 15 and 34 degrees

# Calculate weekly averages
weekly_averages = []
for i in range(0, 30, 7):
  week_temps = daily_temperatures[i:min(i + 7, 30)]  # Handle the last week if it has fewer than 7 days
  weekly_average = np.mean(week_temps)
  weekly_averages.append(weekly_average)

# Display the weekly averages
print("Daily Temperatures:", daily_temperatures)
print("\nWeekly Averages:")
for i, avg in enumerate(weekly_averages):
  print(f"Week {i+1}: {avg:.2f}")

Daily Temperatures: [30 24 24 20 15 15 25 34 25 31 22 19 27 17 19 21 15 32 16 28 21 15 22 15
 32 28 22 18 27 25]

Weekly Averages:
Week 1: 21.86
Week 2: 25.00
Week 3: 21.71
Week 4: 21.71
Week 5: 26.00
